name = "dudutreinamentocpa"
main = "src/index.ts"
compatibility_date = "2024-09-23"

# Servir a aplicação completa compilada (Landing Page + Checkout)
[assets]
directory = "./dist"
binding = "ASSETS"

[vars]
BUCKPAY_TOKEN = "sk_live_sua_chave_aqui"
BUCKPAY_USER_AGENT = "Buckpay API"
WEBHOOK_URL = "https://dudutreinamentocpa.siteverificado.workers.dev/webhook/buckpay"
